### PR TITLE
Z03/tile

### PR DESCRIPTION
**Pull request by AndriiStafiniak**
created a tile component.
without adding all media queries yet.

### CODE REVIEW

**Review by jakub-bartoszek — CHANGES_REQUESTED** [review]
First of all, good job!
Only a few little things i would like you to change before merge.

1. Remove not necessary spaces in Tile.jsx. For example: 
`<Header> Mulan</Header><Year> 2020 </Year>`
2. Maybe not a big deal but you can keep the same distance between every style to make code more clean. 
image
3. I'm not really sure, I just wonder if we should put text like for example this date:
image
Without any `<span>` around it. You can tell me what you think about it. Just casual idea 😄 
4. The last thing i saw is space between "/" and "10".
In the design the space is bigger: 
image
In our page it looks like this: 
image



Despite of those things, rest of the code looks really nice. It's great thing that you used theme colors. I think styles are good, maybe some troubles would appear in the future but for now it looks excelent!

**Comment by AndriiStafiniak** [comment]
you're right, I'm correcting it now

**Comment by AndriiStafiniak** [comment]
I corrected it 😃 Could you please check again?

**Review by jakub-bartoszek — CHANGES_REQUESTED** [review]
Thanks for making changes, now it looks excelent!

I found few more things i didn't notice earlier!

1. To use star icon you can use .svg file I added in /assets folder: 
image
Also you can style it as styled component like I did with other icons in Navigation. Feel free to check that
2. Instead of puting `<MoviePage />` directly in the `<HashRouter>` you can put it in routes, like I did with other pages: 
`<Routes>`
`<Route path="/movie-list" element={<MovieList />} />`
`<Route path="/people" element={<People />} />`
`<Route path="/" element={<MovieList />} />`
`</Routes>`
 I guess you did that to have simple access to this component. If you put it in routes you can acces that by going to http://localhost:3000/#/movie-page
Before that you have to set Route path to "/movie-page"

**Comment by AndriiStafiniak** [comment]
Ready to review 🙂
I use grid template areas, which will allow us to easily manage the component in the future and change it according to the needs of the project

**Comment by szymonbasiul** [comment]
Looks clean ;)

**Pull request merged**
